#cloud-config
package_upgrade: true
packages:
  - git
  - wget
runcmd:
  - mkdir /usr/appinit
  - [ wget, "https://raw.githubusercontent.com/neomorphizm/yc-play/main/labs/install_proxychains.sh", -P, /usr/appinit ]
  - [ wget, "https://raw.githubusercontent.com/neomorphizm/yc-play/main/labs/lab06/install_mongod.sh", -P, /usr/appinit ]
  - [ wget, "https://raw.githubusercontent.com/neomorphizm/yc-play/main/labs/lab06/install_ruby.sh", -P, /usr/appinit ]
  - [ wget, "https://raw.githubusercontent.com/neomorphizm/yc-play/main/labs/lab06/deploy.sh", -P, /usr/appinit ]
  - [ wget, "https://raw.githubusercontent.com/neomorphizm/yc-play/main/labs/lab06/startup-script.sh", -P, /usr/appinit ]
  - chmod +x /usr/appinit/*.sh
  - [ /usr/appinit/startup-script.sh ]
users:
  - default
  - name: alexey
    groups: wheel
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYrA5FR7C5R4JS77Yx/KohOjLGzNvweg8h0hgcll8Xo5CS1nNJ4ebkRlAjjQzPBGrj3P7pFvLLlkRdYnOObMGLTf2Qyj4DMjoYIH51L9SOIJ1IWKshiqbMMQOe79fn2y+mfM9xyR4lo2+NT0wl1kqoxbaqiP1KuKbXgoMh4H6Zqq6Zbh3iSkAMkpC+89NG+xCpsOgGenii9kPlwCND2aEKZeEiJaRY50/KkTaIYEAJCbRwxu8uwrN2n0V9M8HkJKL95Rgpe4TMNjIaoSzW59xxdEheHIc0tmLzko6M4Sy4qgwgvs55w7GiznIrvNLzpawlt6K7WRVf7YHbxy6f4toUt2ZllVq08gCxXS/5oPdryKUF3PTjAYxo99SHezgjXgZ8iBKF3wspIw7xeh6iy6pBwoh7itdE6BfJ5qNYi4PYpJlZ4b1KgyO8mQYGJizKUB6sW0AmoW1tDH+lXXGuhkP3yd/baVCWzv2pWxY1GtAZ+x8Qq46xLkSDpIBGsfGeZEE=
